# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1jG3962VME4N_aZbTkvGJ718mcRMQY8
"""

import streamlit as st
from mrp_engine import run_mrp

st.title("MRP Tool")

if st.button("Correr MRP"):
    df = run_mrp()
    st.dataframe(df)